### ISSUE TITLE
Build error with 8.0.2-rc1

### ISSUE THREAD

**Issue by tuncer** [xmonad/xmonad-contrib#123]
Trying to build xmonad-contrib be036f9 with ghc 8.0.1.20161126:

```
XMonad/Layout/Groups/Helpers.hs:181:22: error:
      Couldn't match type 'WithID l0 Window
                           -> XMonad.Util.Stack.Zipper (G.Group l0 Window)
                           -> XMonad.Util.Stack.Zipper (G.Group l0 Window)'
                     with 'G.ModifySpec'
      Expected type: (G.WithID l0 Window
                      -> XMonad.Util.Stack.Zipper (G.Group l0 Window)
                      -> XMonad.Util.Stack.Zipper (G.Group l0 Window))
                     -> G.GroupsMessage
        Actual type: G.ModifySpec -> G.GroupsMessage
      In the second argument of '(.)' namely 'G.Modify'
      In the expression: sendMessage . G.Modify
      In an equation for 'wrap': wrap = sendMessage . G.Modify
```

Builds fine with 8.0.1.

**Comment by geekosaur** [comment]
On Sat, Nov 26, 2016 at 7:33 PM, Tuncer Ayaz <notifications@github.com>
wrote:

> Trying to build xmonad-contrib be036f9
> <https://github.com/xmonad/xmonad-contrib/commit/be036f9bb9ddeb80e377cb6426d017b5108fac68>
> with ghc 8.0.1.20161126:
>
You might want to hold off on rc1. They ran it against Stackage and found a
bunch of regressions like this that they are fixing for rc2.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by tuncer** [comment]
Glad to hear that. I haven't seen the bulk build report, so didn't know that it's a regression. Do you have links to tickets/reports?

**Comment by tuncer** [comment]
Should we close this until rc2 and try again or leave it open?

**Comment by geekosaur** [comment]
This was chatter in `#ghc` this morning. https://ghc.haskell.org/trac/ghc/ticket/12881 is one ticket opened as a result, but it doesn't look like the problem here. Other typechecking errors might well exist though; if something is known to work with 7.10.3 and 8.0.1 but not rc1, I would suspect an rc1 regression first --- and if there is an actual type issue the older versions let go, let the experts determine that.

(That looks like the only ticket currently open against the rc, aside from a Cabal update request.

(phab's not logging `#ghc` again so I can't link the discussion and suggestion of other regressions to be analyzed)

**Comment by rwbarton** [comment]
The problematic module uses `ImpredicativeTypes`, which has been unsupported for a while. The offending line is (https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Layout/Groups/Helpers.hs#L181)
```
wrap = sendMessage . G.Modify
```
which needs to instantiate `(.)` at `G.ModifySpec`, which I assume must be a polymorphic type. Simple eta expansion
```
wrap ms = sendMessage (G.Modify ms)
```
should avoid the need for `ImpredicativeTypes`.

**Comment by geekosaur** [comment]
Ok, that's fixable. (I didn't think we had any `ImpredicativeTypes` use in contrib. Sigh.)

**Comment by tuncer** [comment]
Closing since there's a fix: #124.
