### ISSUE TITLE
xmonad-contrib-0.13 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [xmonad/xmonad-contrib#235]
The problem is https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid:

~~~
XMonad/Hooks/FadeWindows.hs:132:10: error:
    • No instance for (Semigroup Opacity)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Opacity’
    |
132 | instance Monoid Opacity where
    |          ^^^^^^^^^^^^^^

XMonad/Layout/Mosaic.hs:199:10: error:
    • No instance for (Semigroup (Tree a))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Tree a)’
    |
199 | instance Monoid (Tree a) where
    |          ^^^^^^^^^^^^^^^

XMonad/Hooks/WallpaperSetter.hs:84:10: error:
    • No instance for (Semigroup WallpaperList)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid WallpaperList’
   |
84 | instance Monoid WallpaperList where
   |          ^^^^^^^^^^^^^^^^^^^^
~~~
